name: Build CPU Linux X64

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  DOCKER_BUILDKIT: 1

jobs:
  buildx:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Assign release version
        run: |
          release_version="$(sed -nE 's/.*VSF_VERSION[[:space:]]+"([^"]+)".*/\1/p' Interfaces/VideoSubFinderWXW/MyResource.h | head -1)"
          echo "release_version=${release_version}" >> "$GITHUB_ENV"

      - name: Build cpu (Debian 12)
        run: bash ./Build/Docker/cpu/build.sh

      - name: Test
        run: bash ./Build/Docker/cpu/test.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: videosubfinder-cli-cpu-linux-x64
          path: ./Build/Docker/cpu/out/videosubfinder-cli-cpu-linux-x64.tar.gz
          if-no-files-found: error
          compression-level: 0

      - name: Release draft
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: "${{ env.release_version }}"
          tag_name: "${{ env.release_version }}-ci"
          files: |
            ./Build/Docker/cpu/out/videosubfinder-cli-cpu-linux-x64.tar.gz
          body: "[Github Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
